/**************************************************************************
* Filename:
* ---------
*  ResID\ResID.h : header file
*
* Description:
* ------------
*  Resource IDs cho LuaEngine. Runtime lấy toàn bộ nội dung từ script.lua
*  (thẻ nhớ), nên không có chuỗi tĩnh đóng gói.
*
* This is auto generated by ResEditor.exe
**************************************************************************/

#if !defined _RESID_RESID_H_
#define _RESID_RESID_H_

#ifdef __cplusplus
    extern "C" {
#endif

/* (không có resource nào) */

#ifdef __cplusplus
    }
#endif

#endif  /* _RESID_RESID_H_ */